# theme.toml for the Airspace Hugo theme

name = "domainmedics Hugo"
license = "MIT"
licenselink = ""
description = "Airspace is a Hugo theme built for multipurpose use, like Portfolio, Blog, Business."
homepage = ""
demosite = ""
tags = ["blog",'google-analytics', 'fast', 'modern', 'minimal', 'minimalistic', 'business', 'agency-template', 'white', 'light', 'multilingual', "bootstrap", "company", "portfolio", "projects", "responsive", "domainmedics", "gethugothemes"]
features = ["blog", "company", "responsive", "seo-friendly"]
min_version = "0.87.0"

[author]
  name = "domainmedics"
  homepage = ""

[original]
  name = "Airspace"
  homepage = ""
  repo = ""
