################# English language ################
[en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 1

################ French language ##################
[fr]
languageName = "Français"
languageCode = "en-US"
contentDir = "content/french"
weight = 1

################ Italian language #################
[it]
languageName = "Italiano"
languageCode = "en-US"
contentDir = "content/italian"
weight = 1

################ German language ##################
[de]
languageName = "German"
languageCode = "en-US"
contentDir = "content/german"
weight = 1